title: "Tailpages: Tailwind + Github Pages"
email: harryjwang@gmail.com
description: A Github Pages (Jekyll) template based on TailwindCSS
baseurl: "/tailpages" # the subpath of your site, e.g. /blog
url: "https://harrywang.github.io" # the base hostname & protocol for your site, e.g. http://example.com

google-analytics: G-WCRC1TC2V5

# use false to turn off any social media links
facebook: false
twitter: https://twitter.com/harryjwang
github: https://github.com/harrywang/tailpages

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
