# change the followings to match your Github username and repo name
baseurl: "/LIYUFAN" # the name of your github repo
url: "https://1bowlLIYUFAN.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "LIYUFAN | 李与凡"
description: Personal Page for LIYUFAN

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: LIYUFAN
author-bio: Researcher / Artist / Advanced PM  # change to false to hide
author-image: liyufan.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: CV
  permalink: about
- text: Programs
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
facebook: false
instagram: https://www.instagram.com/1bowl_liyufan/
github: https://github.com/1bowlLIYUFAN
linkedin: https://www.linkedin.com/in/%E4%B8%8E%E5%87%A1-%E6%9D%8E-b7820317a/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com1bowlLIYUFAN/LIYUFAN

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
